name: lint-formatter

on:
  workflow_dispatch:

  push:
    paths:
      - 'include/**/*.h*'
      - 'src/**/*.c*'

jobs:
  lint-formatter-job:
    uses: ultimaker/cura-workflows/.github/workflows/lint-formatter.yml@main
