name: Unit tests - publish

on:
  workflow_run:
    workflows: [Unit tests - run]
    types: [completed]

jobs:
  publish-test-results:
    uses: ultimaker/cura-workflows/.github/workflows/unit-test-post.yml@main
    with:
      workflow_run_json: ${{ github.event.workflow_run }}
    secrets: inherit
