name: Unit tests - publish

on:
  workflow_run:
    workflows: [Unit tests - run]
    types: [completed]

jobs:
  publish-test-results:
    uses: ultimaker/cura-workflows/.github/workflows/unit-test-post.yml@main
    with:
      trigger_workflow_event: ${{ github.event.workflow_run.event }}
      trigger_workflow_conclusion: ${{ github.event.workflow_run.conclusion }}
      trigger_workflow_id: ${{ github.event.workflow_run.workflow_id }}
      trigger_workflow_run_id: ${{ github.event.workflow_run.id }}
    secrets: inherit
